In [1]:
import tensorflow as tf 

In [2]:
a=2
b=3
c=tf.add(a,b,name='add')
print(c)

Tensor("add:0", shape=(), dtype=int32)


In [7]:
sess =tf.Session()
print(sess.run(c))
sess.close()

5


In [8]:
with tf.Session()as sess:
    print(sess.run(c))

5


In [12]:
import tensorflow as tf
x=2
y=3
add_op=tf.add(x,y,name='add')
mult_op=tf.multiply(x,y, name='multiply')
pow_op=tf.pow(add_op,mult_op,name='power')
res=tf.multiply(x,pow_op,name='Useless')
with tf.Session()as sess:
    pout,res_out=sess.run([pow_op,res])
    print(pout)
    print(res_out)


15625
31250


In [19]:
c=tf.constant([[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8]])
a=tf.math.segment_sum(c,tf.constant([0,0,1]))
with tf.Session() as sess:

    print(sess.run(a))


[[0 0 0 0]
 [5 6 7 8]]


In [20]:
c=tf.constant([[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8]])
a=tf.math.unsorted_segment_sum(c,tf.constant([0,1,0]),num_segments=2)
with tf.Session() as sess:
    print(sess.run(a))

[[ 6  8 10 12]
 [-1 -2 -3 -4]]
