whats numpy ?

its a main library in python that deals with scientific computing, it provides high performance multi-dimensional array object ie: can deal with more than one dimensional array (2x2, 3x3....etc), not only but also it facilitates the use of the mathematical operations in case of dealing with such arrays 



traditional arrays(python_lists) vs Numpy arrays


The main benefits of using NumPy arrays should be smaller memory consumption and better runtime behavior. 



# **One dimentional array**

In [0]:
import numpy as np 
#define an array of numpy

my_array=np.array([10,20,30,40])
print(my_array)

[10 20 30 40]


In [0]:
print(type(my_array))

<class 'numpy.ndarray'>


In [0]:
print(my_array.shape) 

(4,)


what does the (4,) means ?
it identifies the number of rows this numpy array contains , ie: 4x1 array or in others words first class array 

to change ana element in the numpy array , simply refere to the element index and assign the your desired value 

In [0]:
my_array[0]=15
print(my_array)

[15 20 30 40]


# **Multidimensional Arrays**

now lets create a multi-dimensional array of dimensions (rank 2 )

In [0]:
my_new_array=np.array([[10,20,30,40],[50,60,70,80]])
print(my_new_array)

[[10 20 30 40]
 [50 60 70 80]]


In [0]:
print(type(my_new_array))

<class 'numpy.ndarray'>


In [0]:
print(my_new_array.shape)

(2, 4)


2x4 array 2 rows and 4 columns 
what if we want to print 2x2 array in numpy ?

In [0]:
x=np.array([[1,2],[3,4]])
print (x)
print(x.shape)

[[1 2]
 [3 4]]
(2, 2)


# **Indexing and Slicing Arrays**

refering to index-value 
it means that we want to call a value by its index , let us see how this is done

In [0]:
y=np.array([1,2,3,4,5,6,7])
print(y)
print (y.shape )
#let us print the first element of this numpy array denoted by the index zero 
#just a reminder the element in the array = index-1
#element value which is equal to one is considered the first element in the numpy 
#with index of zero


print("first element in the numpy array:",y[0])

#if we want to print elements from index 0 to 3
print("first three elements are",y[0:3])

[1 2 3 4 5 6 7]
(7,)
first element in the numpy array: 1
first three elements are [1 2 3]


# **Creating Automatic Arrays**




1.   creating zeros array
2.   creating ones array
3.   creating constant_type arrays
4.   creating identity array(identity_matrix)
5.   creating random_type_arrays



In [0]:
import numpy as np 

#creating an automatic_zeros_array
zero_array=np.zeros((3,3))
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
#creating an automatic ones array
one_array=np.ones((3,3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [0]:
#creating constant type array, here we should choose a number that will be constant
#and pass it to the numpy array , i choose here no.7
c_array=np.full((3,3),7)
print(c_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [0]:
#the identity matrix eye_array
eye_matrix=np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
#the random array
R=np.random.random((3,3))
print(R[0:2])


[[0.30514008 0.17476268 0.46972854]
 [0.50773496 0.87458546 0.4047024 ]]


# **NumPy Data Types** 
we will go for now for 3 main data types in numbers(we wont talk about strings now)

1.   integers 
2.   floats ( pointed numbers )
3.   complex numbers ( rarely used in our course)


In [0]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype) 

int64
float64
int64


# **Basic Mathematical Operations (arithmatic operations )**

In [0]:
import numpy as np

x = np.array([[10,20],[30,40]], dtype=np.float64)
y = np.array([[50,60],[70,80]], dtype=np.float64)
print(x.shape)
print(y.shape)

(2, 2)
(2, 2)


In [0]:
print(x + y)

[[ 60.  80.]
 [100. 120.]]


In [0]:
print(np.add(x, y))

[[ 60.  80.]
 [100. 120.]]


the arithmatic add operation can give the same result in both usage 

In [0]:
print(x - y)


[[-40. -40.]
 [-40. -40.]]


In [0]:
print(np.subtract(x, y))

[[-40. -40.]
 [-40. -40.]]


the arithmatic minus operation can give the same result in both usage 

In [0]:
print(x * y)


[[ 500. 1200.]
 [2100. 3200.]]
[[ 500. 1200.]
 [2100. 3200.]]


In [0]:
print(np.multiply(x, y))

[[ 500. 1200.]
 [2100. 3200.]]


In [0]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [0]:
print(np.sqrt(x))

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


# **More Operations on Arrays:**

 (Dot product, Transpose, Broadcasting)

**1. Dot product versus element wise multiplication**


In [0]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
#print(v.shape)

#print(v.dot(w))
#print(x.dot(v))

print(x.dot(y))


[[19 22]
 [43 50]]


**2. Transpose**

In [0]:
import numpy as np

x=np.array([[1,2],[3,4]])
#x=[1 2]
#[3 4]
print("original matrix",x)
print("transpose matrix",x.T)

original matrix [[1 2]
 [3 4]]
transpose matrix [[1 3]
 [2 4]]


In [0]:
v=np.array([1,2,3])
print("orignal vector",v)
print("transpose vector",v.T)
print(v.shape)

orignal vector [1 2 3]
transpose vector [1 2 3]
(3,)


**3. Broadcasting**

In [0]:
import numpy as np

x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
vv=np.tile(v,(4,1))


#print(vv)
sum_of_vectors=x+vv
print(sum_of_vectors)
#print(x)
#print(v)
#print(x.shape)
#print(v.shape)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [0]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
sum_of_vectors=x+v
print(sum_of_vectors)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
